"""make member and book unique

Revision ID: 22b6b58ea088
Revises: 33786e1755f0
Create Date: 2024-08-18 18:29:39.805699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b6b58ea088'
down_revision = '33786e1755f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_book_member', ['book_id', 'member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_book_member', type_='unique')

    # ### end Alembic commands ###
