"""change Book model

Revision ID: 39412a2f4e03
Revises: 86797b201957
Create Date: 2024-11-02 13:30:36.196196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39412a2f4e03'
down_revision = '86797b201957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('num_pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pages', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
