"""create issued date column

Revision ID: 72bf2eefd9a8
Revises: e8a4dad19604
Create Date: 2024-08-13 16:52:53.974116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bf2eefd9a8'
down_revision = 'e8a4dad19604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.drop_column('issued_date')

    # ### end Alembic commands ###
