"""change column rating to str

Revision ID: 86797b201957
Revises: 22b6b58ea088
Create Date: 2024-11-02 12:47:47.107360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86797b201957'
down_revision = '22b6b58ea088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
